/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderDTO = IDL.Record({
  'id' : IDL.Nat,
  'day' : IDL.Text,
  'status' : IDL.Text,
  'class' : IDL.Text,
  'rollNumber' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'childName' : IDL.Text,
  'parentName' : IDL.Text,
  'foodItem' : IDL.Text,
  'schoolName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMultipleOrders' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeliveredOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [OrderDTO], ['query']),
  'getPendingOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderAsDelivered' : IDL.Func([IDL.Nat], [], []),
  'placeOrder' : IDL.Func([OrderDTO], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderDTO = IDL.Record({
    'id' : IDL.Nat,
    'day' : IDL.Text,
    'status' : IDL.Text,
    'class' : IDL.Text,
    'rollNumber' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'childName' : IDL.Text,
    'parentName' : IDL.Text,
    'foodItem' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMultipleOrders' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeliveredOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [OrderDTO], ['query']),
    'getPendingOrders' : IDL.Func([], [IDL.Vec(OrderDTO)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderAsDelivered' : IDL.Func([IDL.Nat], [], []),
    'placeOrder' : IDL.Func([OrderDTO], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };